# Conclusion

After completing this exploratory analysis, it seems clear that rest has an impact on performance, although marginally so. However, the small impact is not entirely surprising since there are so many variables that go into performance. Teams win more frequently and by greater margins as days of rest between games increase. They shoot better from the 3 point line, grab more offensive rebounds, and force more turnovers. Often the biggest impact of rest is seen going from 0 days of rest to 1 day of rest.

One limiting factor of this analysis is a lack of independence in the data. Each game is recorded as two observations, one for each team. Clearly we know that the performance of one team in a game is not independent of the other team. The pair of observations from each game are associated with one another.

With more time, I would like to get more granular with the analysis and look at player level effects of rest. For example, is there a positional effect? Do smaller players who move around more frequently feel the effect of a lack of rest more than bigger players? How about an age effect? Do older players benefit more from rest? Even still, how does rest affect injury likelihood? These are questions that would require another dataset.