--- 
title: "Exploring the Effects of Rest on Team Performance in the National Basketball Association"
author: "Dipesh Patel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In the National Basketball Association (NBA), there are 30 teams that each play 82 games in a regular season during a roughly 180 day span. This equates to each team having to play about every other day on average. For such a fast paced and strenuous sport where there is constant motion and explosive movements, there seems to be a lot of basketball played in a relatively short time frame. Not surprisingly, the ramifications of such a dense schedule have been part of the discourse of national media outlets for some time. It could even be said that the conversations may have been sparked from the behavior of NBA teams themselves, who frequently sit important players for neither non-injury nor personal related reasons. This behavior implies teams are concerned that players are sometimes not getting enough rest between games. While rest is important for injury prevention, it is also important for performance. I am interested in exploring the impact of rest on the latter. Of course, winning is the ultimate goal in any competitive sport. So how does prior rest impact a team's likelihood of winning? I would also like to examine the effect of time on the impact of rest. Is rest more impactful later in the season than in the beginning where team's are fully recovered after the offseason. Digging deeper, what specific aspects of the game are affected by differences in rest levels? We can look at the parts of the sport where energy plays an important part of success like 3 point shooting, offensive rebounding, and turnover forcing. Also, we can look at how the shot distance distribution changes with rest.